---@meta

---@class BARDebug
---@field ParamsEcho? fun(...: any): ...
---@field TraceEcho? fun(...: any)
---@field TraceFullEcho? fun(maxdepth: number?, maxwidth: number?, maxtableelements: number?, ...: any)

---@class UtilitiesGametype
---@field IsSinglePlayer fun(): boolean
---@field Is1v1 fun(): boolean
---@field IsTeams fun(): boolean
---@field IsBigTeams fun(): boolean
---@field IsSmallTeams fun(): boolean
---@field IsRaptors fun(): boolean
---@field IsScavengers fun(): boolean
---@field IsPvE fun(): boolean
---@field IsCoop fun(): boolean
---@field IsFFA fun(): boolean
---@field IsSandbox fun(): boolean
---@field GetCurrentHolidays fun(): table<string, boolean>?

---@class UtilitiesColor
---@field ToString fun(r: number, g: number, b: number): string
---@field ToStringEx fun(r: number, g: number, b: number, a: number, oR: number, oG: number, oB: number, oA: number): string
---@field ToIntArray fun(r: number, g: number, b: number): number, number, number
---@field ColorIsDark fun(r: number, g: number, b: number): boolean
---@field ConvertColor fun(r: number, g: number, b: number): string

---@class UtilitiesTGA
---@field width number
---@field height number
---@field channels number
---@field pixels number[]

---@class Utilities
---@field [string] any
---@field LoadTGA fun(filename: string): UtilitiesTGA
---@field SaveTGA fun(filename: string, tga: UtilitiesTGA): boolean
---@field NewTGA fun(width: number, height: number, channels: number): UtilitiesTGA
---@field MakeRealTable fun(syncedTable: any): table
---@field GetAllyTeamCount fun(): number
---@field GetAllyTeamList fun(): integer[]
---@field GetPlayerCount fun(): integer?
---@field Gametype UtilitiesGametype
---@field GetScavAllyTeamID fun(): integer?
---@field GetRaptorTeamID fun(): integer?
---@field GetScavTeamID fun(): integer?
---@field GetRaptorAllyTeamID fun(): integer?
---@field IsDevMode fun(): boolean
---@field ShowDevUI fun(): boolean
---@field IsDevModeCached fun(): boolean
---@field CustomKeyToUsefulTable fun(customParams: table): table
---@field SafeLuaTableParser fun(str: string): table?, string?
---@field Color UtilitiesColor
---@field ConvertColor fun(r: number, g: number, b: number): string
---@field GetAccountID fun(playerID: number): number

---@class Lava
---@field isLavaMap boolean
---@field diffuseEmitTex string
---@field normalHeightTex string
---@field level number
---@field grow number
---@field damage number
---@field damageFeatures boolean|number
---@field uvScale number
---@field colorCorrection string
---@field losDarkness number
---@field swirlFreq number
---@field swirlAmp number
---@field specularExp number
---@field shadowStrength number
---@field coastWidth number
---@field coastColor string
---@field coastLightBoost number
---@field lavaParallaxDepth number?
---@field lavaParallaxOffset number?
---@field fogColor string
---@field fogFactor number
---@field fogHeight number
---@field fogAbove number
---@field fogEnabled boolean
---@field fogDistortion number
---@field tideAmplitude number
---@field tidePeriod number
---@field tideRhythm number[][]
---@field effectDamage string
---@field effectBurst string|false
---@field effectBurstSounds table[]
---@field ambientSounds table[]|false

---i18n translator. Callable for a key; also exposes the kikito API (unitName,
---translate, set, …) after i18n_kikito on the mig-i18n branch.
---@class I18NModule
---@field translate fun(key: string, data: table?): string?
---@field load fun(data: table)
---@field set fun(key: string, value: string)
---@field setLocale fun(locale: string)
---@field getLocale fun(): string
---@field loadFile fun(path: string)
---@field unitName fun(unitDefName: string, data: table?): string
---@field setLanguage fun(language: string)
---@field languages table<string, string>
---@overload fun(key: string, data: table?): string

---BAR-added helpers, detached from the Spring table into a single namespace.
---Populated at runtime by init.lua / springOverrides.lua and exposed to the
---widget/gadget sandbox via system.lua.
---@class BAR
---@field I18N I18NModule
---@field Utilities Utilities
---@field Debug BARDebug
---@field Lava Lava
---@field GetModOptionsCopy fun(): table Mutable copy of the mod options table (safe for pairs/ipairs).

---@type BAR
---@diagnostic disable-next-line: missing-fields
BAR = {}
